<?php

namespace AppBundle\Repository;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends \Doctrine\ORM\EntityRepository
{
}
