# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }
    firewalls:
        main:
           anonymous: ~
           form_login:
             login_path: /login
             check_path: /login
             csrf_token_generator: security.csrf.token_manager

           logout:
               path: /logout
               target: /


    encoders:
            AppBundle\Entity\User: bcrypt

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }